function [] = plotDeformation(INFO, PLOT, MESH, DISPLACEMENTS, SOLUTION)

projectDir = INFO.project_directory;
fileName = INFO.file_name;
plotXLimits = PLOT.plot_x_limits;
plotYLimits = PLOT.plot_y_limits;
paperSize = PLOT.paper_size;
paperPosition = PLOT.paper_position;
scaleFactor = PLOT.scale_factor;
numberNodes = MESH.number_nodes;
numberElements = MESH.number_elements;
nodeCoordinates = MESH.node_coordinates;
elementConnectivity = MESH.element_connectivity;
numberPin = DISPLACEMENTS.number_pin;
pinNodes = DISPLACEMENTS.pin_nodes;
numberRoller = DISPLACEMENTS.number_roller;
rollerNodes = DISPLACEMENTS.roller_nodes;
nodeRealDisplacements = SOLUTION.global_displacements;


newFileName = [fileName, '_DEFORMATION.pdf'];
filePath = [projectDir, '\', newFileName];

nodeDisplacements = nodeRealDisplacements * scaleFactor;

% Figure and axes
fi1 = figure(...
	'Name', 'Truss', ...
	'Visible', 'off', ... 
	'Color', [1, 1, 1], ...
	'PaperUnits', 'centimeters', ...
	'PaperSize', paperSize, ...
	'PaperPositionMode', 'auto', ...
	'PaperPosition', paperPosition);
ax1 = axes(...
	'FontSize', 8, ...
	'FontUnits', 'points', ...
	'XLim', plotXLimits, ...
	'YLim', plotYLimits, ...
	'Position', [0.1, 0.065, 0.84, 0.88], ...
	'Box', 'on', ...
	'DataAspectRatioMode', 'manual', ...
	'DataAspectRatio', [1, 1, 1], ...
	'TitleFontSizeMultiplier', 1.5);
set(get(ax1, 'Title'), 'String', ...
	[fileName, ': ', 'Deformation (x', num2str(scaleFactor, '%.2E'), ')']);
set(get(ax1, 'XLabel'), 'String', 'x [m]');
set(get(ax1, 'YLabel'), 'String', 'y [m]');
hold(ax1, 'on');

% Undeformed elements
for numEle = 1 : numberElements
	node1 = elementConnectivity(1, numEle);
	node2 = elementConnectivity(2, numEle);
	X1Coord = nodeCoordinates(1, node1);
	Y1Coord = nodeCoordinates(2, node1);
	X2Coord = nodeCoordinates(1, node2);
	Y2Coord = nodeCoordinates(2, node2);
	plot([X1Coord, X2Coord], [Y1Coord, Y2Coord], ...
		'LineStyle', '--', ...
		'LineWidth', 1, ...
		'Color', [0.6, 0.6, 0.6]);
end

% Undeformed nodes
nodeXCoord = nodeCoordinates(1, :);
nodeYCoord = nodeCoordinates(2, :);
plot(nodeXCoord, nodeYCoord, ...
	'LineStyle', 'none', ...
	'LineWidth', 1, ...
	'Marker', 'o', ...
	'MarkerSize', 3, ...
	'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
	'MarkerFaceColor', [1.0, 1.0, 1.0]);

% Undeformed pin nodes
pinXCoord = nodeCoordinates(1, pinNodes);
pinYCoord = nodeCoordinates(2, pinNodes);
plot(pinXCoord, pinYCoord, ...
	'LineStyle', 'none', ...
	'LineWidth', 1.5, ...
	'Marker', 'o', ...
	'MarkerSize', 3, ...
	'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
	'MarkerFaceColor', [0.0, 0.0, 0.0]);

% Undeformed roller nodes
rollerXCoord = nodeCoordinates(1, rollerNodes);
rollerYCoord = nodeCoordinates(2, rollerNodes);
plot(rollerXCoord, rollerYCoord, ...
	'LineStyle', 'none', ...
	'LineWidth', 1.5, ...
	'Marker', 'o', ...
	'MarkerSize', 3, ...
	'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
	'MarkerFaceColor', [1.0, 1.0, 1.0]);


% Deformed elements
for numEle = 1 : numberElements
	node1 = elementConnectivity(1, numEle);
	node2 = elementConnectivity(2, numEle);
	X1Coord = nodeCoordinates(1, node1);
	Y1Coord = nodeCoordinates(2, node1);
	X2Coord = nodeCoordinates(1, node2);
	Y2Coord = nodeCoordinates(2, node2);
	X1Def = nodeDisplacements(2*node1-1);
	Y1Def = nodeDisplacements(2*node1);
	X2Def = nodeDisplacements(2*node2-1);
	Y2Def = nodeDisplacements(2*node2);
	plot([X1Coord+X1Def, X2Coord+X2Def], [Y1Coord+Y1Def, Y2Coord+Y2Def], ...
		'LineStyle', '-', ...
		'LineWidth', 2.5, ...
		'Color', [0.4, 0.4, 0.4]);
end

% Deformed nodes
for numNod = 1 : numberNodes
	nodeXCoord = nodeCoordinates(1, numNod);
	nodeYCoord = nodeCoordinates(2, numNod);
	nodeXDef = nodeDisplacements(2*numNod-1);
	nodeYDef = nodeDisplacements(2*numNod);
	plot(nodeXCoord+nodeXDef, nodeYCoord+nodeYDef, ...
		'LineStyle', 'none', ...
		'LineWidth', 1, ...
		'Marker', 'o', ...
		'MarkerSize', 4, ...
		'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
		'MarkerFaceColor', [1.0, 1.0, 1.0]);
end

% Deformed pin nodes
for numPin = 1 : numberPin
	node = pinNodes(numPin);
	pinXCoord = nodeCoordinates(1, node);
	pinYCoord = nodeCoordinates(2, node);
	pinXDef = nodeDisplacements(2*node-1);
	pinYDef = nodeDisplacements(2*node);
	plot(pinXCoord+pinXDef, pinYCoord+pinYDef, ...
		'LineStyle', 'none', ...
		'LineWidth', 1.5, ...
		'Marker', 'o', ...
		'MarkerSize', 5, ...
		'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
		'MarkerFaceColor', [0.0, 0.0, 0.0]);
end

% Deformed roller nodes
for numRol = 1 : numberRoller
	node = rollerNodes(numRol);
	rollerXCoord = nodeCoordinates(1, node);
	rollerYCoord = nodeCoordinates(2, node);
	rollerXDef = nodeDisplacements(2*node-1);
	rollerYDef = nodeDisplacements(2*node);
	plot(rollerXCoord+rollerXDef, rollerYCoord+rollerYDef, ...
		'LineStyle', 'none', ...
		'LineWidth', 1.5, ...
		'Marker', 'o', ...
		'MarkerSize', 5, ...
		'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
		'MarkerFaceColor', [1.0, 1.0, 1.0]);
end

% Create pdf file
print(fi1, filePath, '-dpdf');
