function [] = plotTruss(INFO, PLOT, MESH, FORCES, DISPLACEMENTS)

projectDir = INFO.project_directory;
fileName = INFO.file_name;
plotXLimits = PLOT.plot_x_limits;
plotYLimits = PLOT.plot_y_limits;
paperSize = PLOT.paper_size;
paperPosition = PLOT.paper_position;
plotScale = PLOT.plot_scale;
numberNodes = MESH.number_nodes;
numberElements = MESH.number_elements;
nodeCoordinates = MESH.node_coordinates;
elementConnectivity = MESH.element_connectivity;
numberForces = FORCES.number_forces;
forceNodes = FORCES.force_nodes;
forceComponents = FORCES.force_components;
forceAngles = FORCES.force_angles;
pinNodes = DISPLACEMENTS.pin_nodes;
numberRoller = DISPLACEMENTS.number_roller;
rollerNodes = DISPLACEMENTS.roller_nodes;
rollerDirections = DISPLACEMENTS.roller_directions;
rollerAngles = DISPLACEMENTS.roller_angles;


newFileName = [fileName, '_TRUSS.pdf'];
filePath = [projectDir, '\', newFileName];

% Node number text paper displacement
dXPaper = 0.14; %cm
dYPaper = 0.24; %cm
% Node number text real displacement
dXReal = dXPaper / plotScale; %m
dYReal = dYPaper / plotScale; %m

% Figure and axes
fi1 = figure(...
	'Name', 'Truss', ...
	'Visible', 'off', ... 
	'Color', [1, 1, 1], ...
	'PaperUnits', 'centimeters', ...
	'PaperSize', paperSize, ...
	'PaperPositionMode', 'auto', ...
	'PaperPosition', paperPosition);
ax1 = axes(...
	'FontSize', 8, ...
	'FontUnits', 'points', ...
	'XLim', plotXLimits, ...
	'YLim', plotYLimits, ...
	'Position', [0.1, 0.065, 0.84, 0.88], ...
	'Box', 'on', ...
	'DataAspectRatioMode', 'manual', ...
	'DataAspectRatio', [1, 1, 1], ...
	'TitleFontSizeMultiplier', 1.5);
set(get(ax1, 'Title'), 'String', [fileName, ': Truss']);
set(get(ax1, 'XLabel'), 'String', 'x [m]');
set(get(ax1, 'YLabel'), 'String', 'y [m]');
hold(ax1, 'on');

% Roller constrains
for numRol = 1 : numberRoller
	rNode = rollerNodes(numRol);
	rDirection = rollerDirections(numRol);
	rAngle = rollerAngles(numRol);
	C = cos(rAngle * pi / 180);
	S = sin(rAngle * pi / 180);
	if (rDirection == 1)
		rDirVec = [C; S];
	else
		rDirVec = [-S; C];
	end
	[drawSeg] = getRollerLines(nodeCoordinates(:, rNode), rDirVec, plotScale);
	for seg = 1 : 2
		plot(drawSeg(2*seg-1, :), drawSeg(2*seg, :), ...
		'LineStyle', '-', ...
		'LineWidth', 1, ...
		'Marker', 'none', ...
		'Color', [0.0, 0.0, 0.0]);	
	end
end

% Elements
for numEle = 1 : numberElements
	node1 = elementConnectivity(1, numEle);
	node2 = elementConnectivity(2, numEle);
	X1Coord = nodeCoordinates(1, node1);
	Y1Coord = nodeCoordinates(2, node1);
	X2Coord = nodeCoordinates(1, node2);
	Y2Coord = nodeCoordinates(2, node2);
	plot([X1Coord, X2Coord], [Y1Coord, Y2Coord], ...
		'LineStyle', '-', ...
		'LineWidth', 2.5, ...
		'Color', [0.7, 0.7, 0.7]);
end

% Forces vectors
for numFor = 1 : numberForces
	fNode = forceNodes(numFor);
	fCompXiYi = forceComponents(:, numFor);
	fAngle = forceAngles(numFor);
	C = cos(fAngle * pi / 180);
	S = sin(fAngle * pi / 180);
	T = [C, S; -S, C];
	fCompXY = T' * fCompXiYi;
	fDirVec = fCompXY / norm(fCompXY);
	[drawSeg] = getForceArrow(nodeCoordinates(:, fNode), fDirVec, 14, plotScale);
	for seg = 1 : 3
	plot(drawSeg(2*seg-1, :), drawSeg(2*seg, :), ...
		'LineStyle', '-', ...
		'LineWidth', 1.3, ...
		'Marker', 'none', ...
		'Color', [0.0, 0.0, 0.0]);
	end
end

% Nodes
nodeXCoord = nodeCoordinates(1, :);
nodeYCoord = nodeCoordinates(2, :);
plot(nodeXCoord, nodeYCoord, ...
	'LineStyle', 'none', ...
	'LineWidth', 1, ...
	'Marker', 'o', ...
	'MarkerSize', 4, ...
	'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
	'MarkerFaceColor', [1.0, 1.0, 1.0]);

% Pin nodes
pinXCoord = nodeCoordinates(1, pinNodes);
pinYCoord = nodeCoordinates(2, pinNodes);
plot(pinXCoord, pinYCoord, ...
	'LineStyle', 'none', ...
	'LineWidth', 1.5, ...
	'Marker', 'o', ...
	'MarkerSize', 5, ...
	'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
	'MarkerFaceColor', [0.0, 0.0, 0.0]);

% Roller nodes
rollerXCoord = nodeCoordinates(1, rollerNodes);
rollerYCoord = nodeCoordinates(2, rollerNodes);
plot(rollerXCoord, rollerYCoord, ...
	'LineStyle', 'none', ...
	'LineWidth', 1.5, ...
	'Marker', 'o', ...
	'MarkerSize', 5, ...
	'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
	'MarkerFaceColor', [1.0, 1.0, 1.0]);

% Force nodes
forceXCoord = nodeCoordinates(1, forceNodes);
forceYCoord = nodeCoordinates(2, forceNodes);
plot(forceXCoord, forceYCoord, ...
	'LineStyle', 'none', ...
	'LineWidth', 0.1, ...
	'Marker', 'o', ...
	'MarkerSize', 1.3, ...
	'MarkerEdgeColor', [0.0, 0.0, 0.0], ...
	'MarkerFaceColor', [0.0, 0.0, 0.0]);

% Node numbers
for numNod = 1 : numberNodes
	nodeXCoord = nodeCoordinates(1, numNod);
	nodeYCoord = nodeCoordinates(2, numNod);
	text(nodeXCoord+dXReal, nodeYCoord+dYReal, num2str(numNod, '%d'), ...
		'FontSize', 6, ...
		'FontWeight', 'bold', ...
		'HorizontalAlignment', 'center', ...
		'VerticalAlignment', 'middle', ...
		'BackgroundColor', [1.0, 1.0, 1.0], ...
		'Margin', 0.1);
end

% Element numbers
for numEle = 1 : numberElements
	node1 = elementConnectivity(1, numEle); 
	node2 = elementConnectivity(2, numEle); 
	midPoint = (nodeCoordinates(:, node1) + nodeCoordinates(:, node2)) / 2;
	text(midPoint(1), midPoint(2), num2str(numEle, '%d'), ...
		'FontSize', 6, ...
		'HorizontalAlignment', 'center', ...
		'VerticalAlignment', 'middle', ...
		'BackgroundColor', [1.0, 1.0, 1.0], ...
		'Margin', 0.1);
end

% Create pdf file
print(fi1, filePath, '-dpdf');